Repository jellyfin/jellyfin-plugin-anidb, pull requests merged in 2022-03, with the labels that each got.

#26 Add original title metadata
  Jellyfin.Plugin.AniDB/Configuration/PluginConfiguration.cs
  Jellyfin.Plugin.AniDB/Configuration/configPage.html
  Jellyfin.Plugin.AniDB/Providers/AniDB/Metadata/AniDbSeriesProvider.cs
Labels: feature

#30 Use meta ci
  .github/workflows/build-dotnet.yml
  .github/workflows/build.yaml
  .github/workflows/bump-version.yaml
  .github/workflows/changelog.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/command-dispatch.yaml
  .github/workflows/command-rebase.yaml
  .github/workflows/label-sync.yml
  .github/workflows/publish.yaml
  .github/workflows/scan-codeql.yaml
  .github/workflows/sync-labels.yaml
  .github/workflows/test-dotnet.yml
  .github/workflows/test.yaml
  .github/workflows/update-release-draft.yml
  build.yaml
Labels: ci, chore

#27 Improve AniDB ID searching and matching
  CONTRIBUTORS.md
  Jellyfin.Plugin.AniDB/Configuration/PluginConfiguration.cs
  Jellyfin.Plugin.AniDB/Configuration/configPage.html
  Jellyfin.Plugin.AniDB/Providers/AniDB/Metadata/AniDbSeriesProvider.cs
  Jellyfin.Plugin.AniDB/Providers/equals_check.cs
Labels: bug, chore

#19 Use proper normalization form
  Jellyfin.Plugin.AniDB/Providers/AniDB/Identity/AniDbTitleMatcher.cs
Labels: bug
